### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by debrisapron** [nick-thompson/elementary#12]
Apologies if I'm missing something obvious but I can't find the code for either the runtime or the library? Very interested in this project & was hoping to get a look at the internals with an eye to maybe contributing somehow.

**Comment by debrisapron** [comment]
Sorry, just saw the closed issue so am closing. I'll just say that it would be good to include a note explaining this in the README

**Comment by nick-thompson** [comment]
Yea, thanks @debrisapron I do want to clarify this in the docs. It's part of the larger question that I'm still debating about how much of the project I do actually want to open source, and how can I correctly address the licensing of that piece. In progress, hopefully I'll have a decision soon!
