### ISSUE TITLE
events module missing in browser environment

### ISSUE THREAD

**Issue by caged** [nick-thompson/elementary#13]
Running the latest version 0.10.4.

Elementary relies on node's built-in events module, however that module doesn't exist in browsers.  This causes issues when installing and using the elementary-audio npm package.  You likely need to bundle the [events](https://github.com/browserify/events) browser implementation for browser builds of elementary audio.  

He's a sample repo that reproduces the error: https://github.com/caged/ea-test.  Here's an example of the error:
```
> esbuild index.js --bundle --minify --outfile=public/bundle.js

 > node_modules/@nick-thompson/elementary/dist/elementary.min.js:1:13: error: Could not resolve "events" (use "--platform=node" when building for node)
    1 │ import A from"events";var I={sin:"sin",cos:"cos",tan:"tan",tanh:"tanh",asinh:"asinh",ln:"ln",log:"log",log2:"log2",ceil:"ceil",floor:"floor",sqrt...
      ╵
```

**Workaround:** You can workaround this by running `npm install --save events` in your own project.  

You may need to create a UMD build using whatever bundler you're using.

**Comment by nick-thompson** [comment]
Believe this has been resolved; please reopen if I have that wrong!
