### ISSUE TITLE
issue with command "elementary"

### ISSUE THREAD

**Issue by MaxFmr** [nick-thompson/elementary#15]
Hi, what a fantastic project here ! My issue is tht the command "elementary" does not work on my mac or PC.

I've configured with my api key and i think i followed all instuctions in "get started" part of the documentation , after cloning the examples repository, installed the package and pointig the right place to start de code, "elementary" is not recognized as a command. 

Thanks for your response, i really want to become an audio programmer ;)

**Comment by nick-thompson** [comment]
Hey @MaxFmr thank you! I'm happy to see your excitement!

Ok so you've followed the command line installation instructions and ran the following command?

```
$ curl -fsSL https://www.elementary.audio/install.sh | sh
```

After that command runs it prints a message saying,

```
Manually add the directory to your $HOME/$SHELL_PROFILE (or similar)
  export ELEM_INSTALL_DIR="$ELEM_INSTALL_DIR"
  export PATH="$ELEM_INSTALL_DIR/bin:$PATH"
Then Run 'elementary --help' to get started (you may need to restart your shell session to reload your profile configuration)
```

Were you able to run that part? `$ELEM_INSTALL_DIR` by default will point to `$HOME/.elementary` on MacOS. On Windows, you will need to manually pull the binary files to the appropriate directory for your shell to find them. Let me know if that helps!

**Comment by MaxFmr** [comment]
Hey @nick-thompson thank you so much, it was the first time that i configured my zsh manually, and there was some mistakes, now it's fine ! The command is running , thanks again fore your response. Let's make some music with my own js programs ;) !

**Comment by nick-thompson** [comment]
You're welcome, enjoy!
