### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by YitziG** [nick-thompson/elementary#17]
https://github.com/nick-thompson/elementary/blob/63ffce1da0f380e9afd4117a9e02522335d8ef40/README.md?plain=1#L24

Does nothing. Perhaps missing an `sh install.sh` instruction?

**Comment by nick-thompson** [comment]
I just pushed a set of changes that I believe resolves this. If you have the latest CLI binary and you re-run `npm install` it should be working again. Apologies for that!

I'm going to close this issue; please reopen if you still have trouble with it.
