### ISSUE TITLE
What is elementary-core?

### ISSUE THREAD

**Issue by arvind-iyer** [nick-thompson/elementary#2]
I see the examples all reference a library called 'elementary-core' that is not on npm and no other installation instructions are provided on this repo either.

**Comment by dennyabrain** [comment]
Hi @arvind-iyer, I had the same doubt when I was going through the docs and took me a while to understand what it means by "Elementary is a JavaScript runtime".

so basically once you have installed elementary in your project by running `npm install @nick-thompson/elementary`, you should then run your scripts by running `./node_modules/.bin/elementary YOUR_SCRIPT.js` this way, the elementary runtime would load elementary-core and your script will be able to access it.
