### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by konsumer** [nick-thompson/elementary#5]
Where is the source for `elementary-core` or `@nick-thompson/elementary`? I can't seem to find it on your github.

I did this to look at some of the source:

```sh
npm pack @nick-thompson/elementary
tar xvzf nick-thompson-elementary*.tgz
```

Which has a bit, but not `elementary-core` (which is also not in npm), and it contains binary runtimes in `bin/`. Is this not open-source?

**Comment by nick-thompson** [comment]
Indeed, it is currently private! See here for a similar discussion: https://github.com/nick-thompson/elementary/discussions/4

Currently I anticipate that `elementary-core` will remain private, and I am in the process of updating the licensing to make that more clear

**Comment by konsumer** [comment]
Ah yes, sorry I didn't see that discussion. I will close this issue and continue discussion over there.
